# Generated by Django 5.0.14 on 2026-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=10)),
                ('Track', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('Updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
